name: CI Build

on:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

env:
  IMAGE: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/myapp:${{ github.sha }}
  ECR_REPO: myapp
  GITOPS_REPO: ganjivasu/myapp-gitops
  DEPLOYMENT_PATH: myapp/dev/deployment.yaml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.AWS_ROLE }}
        aws-region: us-east-1

    - name: Login to ECR
      run: |
        aws ecr get-login-password \
        | docker login --username AWS --password-stdin \
        ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com

    - name: Build and Push Image
      run: |
        IMAGE_TAG=${GITHUB_SHA}
        docker build -t $IMAGE .
        docker push $IMAGE
        
        # Get the immutable digest
        IMAGE_DIGEST=$(aws ecr describe-images \
          --repository-name $ECR_REPO \
          --image-ids imageTag=$GITHUB_SHA \
          --query 'imageDetails[0].imageDigest' --output text)
        IMAGE=$ECR_REGISTRY/$ECR_REPO@$IMAGE_DIGEST



    - name: Checkout GitOps repo
      uses: actions/checkout@v4
      with:
        repository: ${{ env.GITOPS_REPO }}
        token: ${{ secrets.GITHUBTOKEN }}   # Use the PAT
        path: gitops

    - name: Update image tag in deployment.yaml
      run: |
        sed -i "s|image: .*|image: $IMAGE|" gitops/${{ env.DEPLOYMENT_PATH }}

    - name: Commit and push to GitOps repo
      run: |
        cd gitops
        git config user.name "ci-bot"
        git config user.email "ci-bot@example.com"
        git add ${{ env.DEPLOYMENT_PATH }}
        git commit -m "Deploy new image: $GITHUB_SHA"
        git push origin ${{ env.GITOPS_BRANCH }}

    # Create PR for PT promotion
    - name: Create PR to PT
      run: |
        cd gitops
        git checkout -b promote-to-pt
        cp myapp/dev/deployment.yaml myapp/pt/deployment.yaml
        git add myapp/pt/deployment.yaml
        git commit -m "Promote image to PT: $GITHUB_SHA"
        git push origin promote-to-pt
        gh pr create --title "Promote to PT: $GITHUB_SHA" \
                     --body "Automatic promotion from Dev" \
                     --base main --head promote-to-pt
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}

    # Create PR for QA promotion
    - name: Create PR to QA
      run: |
        cd gitops
        git checkout -b promote-to-qa
        cp myapp/dev/deployment.yaml myapp/qa/deployment.yaml
        git add myapp/qa/deployment.yaml
        git commit -m "Promote image to QA: $GITHUB_SHA"
        git push origin promote-to-qa
        gh pr create --title "Promote to QA: $GITHUB_SHA" \
                     --body "Automatic promotion from Dev" \
                     --base main --head promote-to-qa
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}

    # Create PR for QA promotion
    - name: Create PR to Prod
      if: success()
      run: |
        cd gitops
        git checkout -b promote-to-prod
        cp myapp/dev/deployment.yaml myapp/prod/deployment.yaml
        git add myapp/prod/deployment.yaml
        git commit -m "Promote image to Prod: $GITHUB_SHA"
        git push origin promote-to-prod
        gh pr create --title "Promote to Prod: $GITHUB_SHA" \
                     --body "Automatic promotion from Dev" \
                     --base main --head promote-to-prod
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
