name: CI Build

on:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

env:
  IMAGE: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/myapp:${{ github.sha }}
  ECR_REPO: myapp
  GITOPS_REPO: ganjivasu/myapp-gitops
  DEPLOYMENT_PATH: myapp/dev/deployment.yaml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.AWS_ROLE }}
        aws-region: us-east-1

    - name: Login to ECR
      run: |
        aws ecr get-login-password \
        | docker login --username AWS --password-stdin \
        ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com

    - name: Build and Push Image
      run: |
        IMAGE=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/myapp:${{ github.sha }}
        docker build -t $IMAGE .
        docker push $IMAGE


    - name: Checkout GitOps repo
      uses: actions/checkout@v4
      with:
        repository: ${{ env.GITOPS_REPO }}
        path: myapp

    - name: Update image tag in deployment.yaml
      run: |
        sed -i "s|image: .*|image: $IMAGE|" myapp-gitops/${{ env.DEPLOYMENT_PATH }}

    - name: Commit and push to GitOps repo
      run: |
        cd gitops
        git config user.name "ci-bot"
        git config user.email "ci-bot@example.com"
        git add ${{ env.DEPLOYMENT_PATH }}
        git commit -m "Deploy new image: $GITHUB_SHA"
        git push origin ${{ env.GITOPS_BRANCH }}
