name: CI Build & GitOps Promotion

on:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: write

env:
  AWS_REGION: us-east-1
  ECR_REPO: myapp
  ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com
  GITOPS_REPO: ganjivasu/myapp-gitops

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      immutable_image: ${{ steps.image.outputs.immutable_image }}

    steps:
      - uses: actions/checkout@v3

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::281762848319:role/github-actions-ecr-role
          aws-region: us-east-1

      - name: Login to ECR
        run: aws ecr get-login-password | docker login --username AWS --password-stdin $ECR_REGISTRY

      - name: Build & Push Image
        run: |
          IMAGE="$ECR_REGISTRY/$ECR_REPO:$GITHUB_SHA"
          docker build -t "$IMAGE" .
          docker push "$IMAGE"
      
          DIGEST=$(aws ecr describe-images \
            --repository-name "$ECR_REPO" \
            --image-ids imageTag="$GITHUB_SHA" \
            --query 'imageDetails[0].imageDigest' \
            --output text)
      
          IMMUTABLE_IMAGE="$ECR_REGISTRY/$ECR_REPO@$DIGEST"
      
          echo "$IMMUTABLE_IMAGE" > immutable_image.txt

      - name: Upload immutable image
        uses: actions/upload-artifact@v4
        with:
          name: immutable-image
          path: immutable_image.txt


      #- name: DEBUG build output
       # run: |
        #  echo "STEP OUTPUT: ${{ steps.image.outputs.immutable_image }}"


      - name: Checkout GitOps repo
        uses: actions/checkout@v4
        with:
          repository: ${{ env.GITOPS_REPO }}
          token: ${{ secrets.GITHUBTOKEN }}
          path: gitops

      - name: Promote environments
        run: |
          IMAGE=$(cat immutable_image.txt)
          chmod +x promotion.sh
          ./promotion.sh dev "$IMAGE"
          ./promotion.sh pt  "$IMAGE"
          ./promotion.sh qa  "$IMAGE"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}



  deploy-prod:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: prod
  
    steps:
      - uses: actions/checkout@v3
  
      - uses: actions/checkout@v4
        with:
          repository: ${{ env.GITOPS_REPO }}
          token: ${{ secrets.GITHUBTOKEN }}
          path: gitops
  
      - name: Download immutable image
        uses: actions/download-artifact@v4
        with:
          name: immutable-image
  
      - name: Promote to Prod
        run: |
          IMAGE=$(cat immutable_image.txt)
          echo "USING IMAGE = $IMAGE"
          chmod +x promotion.sh
          ./promotion.sh prod "$IMAGE"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}






