name: CI Build & GitOps Promotion

on:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  ECR_REPO: myapp
  ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com
  GITOPS_REPO: ganjivasu/myapp-gitops
  DEV_PATH: myapp/dev/deployment.yaml
  PT_PATH: myapp/pt/deployment.yaml
  QA_PATH: myapp/qa/deployment.yaml
  PROD_PATH: myapp/prod/deployment.yaml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    #Checkout App repo
    - name: Checkout App Repo
      uses: actions/checkout@v3

    - name: Make promotion script executable
      run: chmod +x promotion.sh

    #Configure AWS credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::281762848319:role/github-actions-ecr-role
        aws-region: ${{ env.AWS_REGION }}
        
    #Verify AWS identity
    - name: Verify AWS identity
      run: aws sts get-caller-identity

    #Login to ECR
    - name: Login to ECR
      run: |
        aws ecr get-login-password | docker login --username AWS --password-stdin $ECR_REGISTRY

    #Build & push immutable image
    - name: Build and Push Image
      run: |
        IMAGE_TAG=${GITHUB_SHA}
        IMAGE=$ECR_REGISTRY/$ECR_REPO:$IMAGE_TAG

        docker build -t $IMAGE .
        docker push $IMAGE

        # Get immutable digest
        DIGEST=$(aws ecr describe-images \
          --repository-name $ECR_REPO \
          --image-ids imageTag=$IMAGE_TAG \
          --query 'imageDetails[0].imageDigest' --output text)

        IMMUTABLE_IMAGE=$ECR_REGISTRY/$ECR_REPO@$DIGEST
        echo "IMMUTABLE_IMAGE=$IMMUTABLE_IMAGE" >> $GITHUB_ENV

    #Checkout GitOps repo
    - name: Checkout GitOps repo
      uses: actions/checkout@v4
      with:
        repository: ${{ env.GITOPS_REPO }}
        token: ${{ secrets.GITHUBTOKEN }}
        path: gitops

    #Update Dev deployment
    - name: Update Dev deployment.yaml
      run: |
        sed -i "s|image: .*|image: $IMMUTABLE_IMAGE|" gitops/${{ env.DEV_PATH }}

    #Commit & push Dev
    - name: Commit and push Dev
      run: |
        cd gitops
        git config user.name "ci-bot"
        git config user.email "ci-bot@example.com"
        git add ${{ env.DEV_PATH }}
        git commit -m "Deploy immutable image $GITHUB_SHA to Dev" || echo "No changes to commit"
        git push origin main
        
    #Configure kubectl
    - name: Configure kubectl for EKS
      run: |
        aws eks update-kubeconfig \
          --region $AWS_REGION \
          --name myapp-cluster

    #Verify kubectl can authenticate using kubeconfig
    - name: Sanity check EKS access
      run: |
        kubectl config current-context
        kubectl get nodes
        kubectl auth can-i get jobs -n dev

    - name: Install ArgoCD CLI
      run: |
        curl -sSL -o argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
        chmod +x argocd
        sudo mv argocd /usr/local/bin/
        
    #Wait for ArgoCD app sync
    - name: Wait for ArgoCD app sync
      run: |
        argocd login $ARGOCD_SERVER \
          --username admin \
          --password $ARGOCD_PASSWORD \
          --insecure
    
        argocd app wait myapp-dev \
          --health \
          --sync \
          --timeout 600

    # Wait for ArgoCD to sync
    - name: Wait for ArgoCD sync
      run: sleep 90

    #Wait for smoke test job to appear
    - name: Wait for smoke test job
      run: |
        for i in {1..36}; do
          kubectl get job myapp-smoke-test -n dev && break
          echo "Waiting for ArgoCD to create smoke test job..."
          sleep 10
        done

    #Wait for Dev smoke test to complete
    - name: Wait for smoke test to complete
      run: |
        argocd app wait myapp-dev \
          --sync \
          --health \
          --timeout 300

    # Promote to PT
    - name: Promote to PT
      run: bash promotion.sh pt
      env:
        IMMUTABLE_IMAGE: ${{ env.IMMUTABLE_IMAGE }}
        GITHUB_SHA: ${{ github.sha }}
        GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}

    # Promote to QA
    - name: Promote to QA
      run: bash promotion.sh qa
      env:
        IMMUTABLE_IMAGE: ${{ env.IMMUTABLE_IMAGE }}
        GITHUB_SHA: ${{ github.sha }}
        GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}

    # Promote to Prod
    - name: Promote to Prod
      if: success()
      run: bash promotion.sh prod
      env:
        IMMUTABLE_IMAGE: ${{ env.IMMUTABLE_IMAGE }}
        GITHUB_SHA: ${{ github.sha }}
        GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}

